# CI for product catalog service

name: product-catalog-ci

on:
  push:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Go 1.22
          uses: actions/setup-go@v2
          with:
            go-version: 1.22
              
        - name: Build
          run: |
               cd src/product-catalog
               go mod download 
               go build -o product-catalog-service main.go

        - name: unit tests
          run: |
               cd src/product-catalog
               go test ./...


    code-quality:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup Go 1.22
            uses: actions/setup-go@v2
            with:
              go-version: 1.22

          - name: Run golangci-lint
            run: |
                  go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
                  golangci-lint run ./...

    docker:
        runs-on: ubuntu-latest

        needs: build

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: install docker
            uses: docker/setup-buildx-action@v1

          - name: Login to DockerHub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_TOKEN }}

          - name: Build and Push Docker image
            uses: docker/build-push-action@v6
            with:
              context: src/product-catalog
              file: src/product-catalog/Dockerfile
              push: true
              tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}

    updatek8s:
        runs-on: ubuntu-latest

        needs: docker

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.TOKEN }}

            - name: Update tag k8s deployment manifest
              run: |
                   sed -i 's|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}|g' kubernetes/productcatalog/deploy.yaml

            - name: commit and push changes
              run: |
                   git config --global user.email "emmexgdc@gmail.com"
                   git config --global user.name "emmexgdc"
                   git add kubernetes/productcatalog/deploy.yaml
                   git commit -m "[CI]: Update deployment image tag"
                   git push